# model configuration variables
args:
  audio_path: "../data/"
  sr: 22050
  nfft: 2048
  hoplen: 1024
  init_downbeat: False  # whether to set first detected beat to first downbeat
  target_pattern: "B"  # target output beat length from files

# input filenames
flnA: "pachelbel.mp3" # content file
flnB: "bongo-loop.mp3" # style file

flnLogMagSpectrogram: 'TEST_log_mag_spectro_pachelbelbongo-loop-GPU.npy'  # output of optimization (extension should be .npy)

# TODO
n: 2048
eps: 1

# paths
outputs_path: "../outputs/"
audio_results_path: "../outputs/audio_results/"